# Site/SEO settings
email: 
baseurl: ""
permalink: /:title/
google_analytics: 

name: Samuel Heinrich Spiker
title: Spiker's Berlin
description: >
  Digital edition of Samuel's Spiker 1833 Guide to Berlin
url: 
twitter_username: sammeltassen
default_img: 
social:
  - name: twitter
    url: https://twitter.com/sammeltassen
  - name: github
    url: https://github.com/sammeltassen

# Contact settings
contact_img: 
formcarry: 

# Disqus settings
disqus: 

# MailChimp settings
mailchimp_action: 
mailchimp_input: 

# Author settings
author:
  - name: Samuel Heinrich Spiker
    bio: 
    url: https://de.wikipedia.org/wiki/Samuel_Heinrich_Spiker

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: false
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'Tag'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
